sudo: required
language: go

go:
  - 1.12.5

services:
  - docker

script:
  - export GO111MODULE="on"
  - go test -tags 's3 metadata' -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg github.com/aerokube/selenoid,github.com/aerokube/selenoid/session,github.com/aerokube/selenoid/config,github.com/aerokube/selenoid/protect,github.com/aerokube/selenoid/service,github.com/aerokube/selenoid/upload
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.buildStamp=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.gitRevision=`git describe --tags || git rev-parse HEAD` -s -w"
  - gox -os "linux darwin windows" -arch "amd64" -osarch="windows/386" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags "-X main.buildStamp=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.gitRevision=`git describe --tags || git rev-parse HEAD` -s -w"

install: 
  - go get -u github.com/mitchellh/gox # cross compile

deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: travis/docker-push.sh latest
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: travis/docker-push.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: travis/docker-push.sh latest-release
    skip_cleanup: true
    on:
      tags: true      
  - provider: script
    script: travis/docs.sh latest
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: travis/docs.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true

after_success:
- bash <(curl -s https://codecov.io/bash) -F unittests
